### ISSUE TITLE
Align for equations with nested matrix block

### ISSUE THREAD

**Issue by chengfzy** [cmhughes/latexindent.pl#212]
I use **\mqty[]** in the [physis](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/physics/physics.pdf) for simplify the small matrix block, consider the below file
```
\begin{equation}
    \begin{aligned}
        x =& x^2 \mqty[a_{11}  & a_{12} \\ a_{21} & a_{22}] =& f(x) \\
        y =& f(y) =& y^2 \\
        z =& f(z) =& z^2
    \end{aligned}
\end{equation}
```

the default output after I using latexindent.pl is
```
\begin{equation}
    \begin{aligned}
        x = & x^2 \mqty[a_{11}  & a_{12} \\ a_{21} & a_{22}] =&f(x)\\
        y = & f(y) =            & y^2    \\
        z = & f(z)            = & z^2
    \end{aligned}
\end{equation}
```
, and the result I expect is
```
\begin{equation}
    \begin{aligned}
        x = & x^2 
            \mqty[
                a_{11} & a_{12} \\
                a_{21} & a_{22}
            ] =                                                & f(x) \\
        y = & f(y) =                                           & y^2  \\
        z = & f(z) =                                           & z^2
    \end{aligned}
\end{equation}
```
or like this
```
\begin{equation}
    \begin{aligned}
        x = & x^2 
            \mqty[
                a_{11}  & a_{12} \\
                a_{21} & a_{22}
            ] =                                                & f(x) \\
        y = & f(y) =                                           & y^2  \\
        z = & f(z) =                                           & z^2
    \end{aligned}
\end{equation}
```
Is there an option to do this? Thanks.

**Comment by cmhughes** [comment]
Thanks for this. 

I'm afraid that your desired output is not possible with the current implementation of `latexindent`. The issue you describe is the same one detailed within https://github.com/cmhughes/latexindent.pl/issues/85 and https://github.com/cmhughes/latexindent.pl/issues/162 and it is because you have nested code blocks that you would like aligned at different ampersands. 

I'll add a reference to this issue to both of the other open issues, and close this one as a duplicate. 

I hope to be able to resolve this behaviour at some point in the future, but it will require a large amount of work, and I don't have capacity for it at the moment. My apologies again.

**Comment by cmhughes** [comment]
Update! see https://github.com/cmhughes/latexindent.pl/issues/85 :) release to follow soon :)

**Comment by cmhughes** [comment]
Released as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.10.1, uploaded to ctan, you should be able to get it using your TeX distribution manager within about 24 hours, ctan allowing.
