### ISSUE TITLE
Unwanted indent with inline math having unmatched parentheses

### ISSUE THREAD

**Issue by bersbersbers** [cmhughes/latexindent.pl#234]
I believe `latexindent` gets confused by constructs such as `(0, 1]`, see here:

```
Bla ($x \in (0, 1]$ and $x \in [0, 1]$)

Bla ($x \in (0, 1]$ and $x \in [0, 1]$)

Bla ($x \in (0, 1]$ and $x \in [0, 1]$)
```

I would expect no change by `latexindent`, but I am getting
```
Bla ($x \in (0, 1]$ and $x \in [0, 1]$)

        Bla ($x \in (0, 1]$ and $x \in [0, 1]$)

Bla ($x \in (0, 1]$ and $x \in [0, 1]$)
```

```
> latexindent --version
3.8.3, 2020-11-06
```

**Comment by cmhughes** [comment]
Thanks for this, I'll have a look at it over the next few days and get back to you :)

**Comment by cmhughes** [comment]
If we employ the code from https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-specialbeforecommand-yaml by running the command
```
latexindent.pl cmh.tex -y="specialBeginEnd:specialBeforeCommand:1"
```
then we receive the desired output:
```tex
Bla ($x \in (0, 1]$ and $x \in [0, 1]$)

Bla ($x \in (0, 1]$ and $x \in [0, 1]$)

Bla ($x \in (0, 1]$ and $x \in [0, 1]$)
```

The reason for this is that otherwise `latexindent` will first find the `\in` command and allows round matching parenthesis. 

The current implementation (described in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#conflicting-poly-switches-nested-code-blocks) isn't ideal. I'm exploring alternative strategies. 

In the mean time, I hope that the above works for you :)

**Comment by bersbersbers** [comment]
Thanks for this workaround. However, while it works for the MWE I posted, it does not work for this one:
```
We have $x \in
[0, 1]$ and ...
```

nor this one:
```
We have $x \in
(0, 1)$ and ...
```

nor this one:
```
numbers in $[0,
1]$ are ...
```

In all cases, `latexindent bug.tex -y="specialBeginEnd:specialBeforeCommand:1"` indents the 2nd line (even twice, in the last example).

Do you happen to have an equally simply workaround for this case as for the initial one?

**Comment by bersbersbers** [comment]
Never mind, I guess these are expected, and can be turned off using `-y="indentRules:inlineMath:''"`.
