### ISSUE TITLE
Missing dependencies in Debian

### ISSUE THREAD

**Issue by drupol** [cmhughes/latexindent.pl#235]
Hello,

I'm trying to use `latexindent.pl` in this docker image: [dante-ev/docker-texlive](https://github.com/dante-ev/docker-texlive).

The error that I get is:

```
$ docker-compose run texlive latexindent
Creating continuouslatex_texlive_run ... done
Can't locate Log/Dispatch/File.pm in @INC (you may need to install the Log::Dispatch::File module) (@INC contains: /usr/share/texlive/texmf-dist/scripts/latexindent /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.0 /usr/local/share/perl/5.32.0 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/texlive/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 24.
BEGIN failed--compilation aborted at /usr/share/texlive/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 24.
Compilation failed in require at /usr/share/texlive/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
BEGIN failed--compilation aborted at /usr/share/texlive/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
Compilation failed in require at /usr/bin/latexindent line 30.
BEGIN failed--compilation aborted at /usr/bin/latexindent line 30.
```

Could you please tell me what are the dependencies required to get `latexindent.pl` working?

The Debian based Dockerfile related to that Docker image is here: https://github.com/dante-ev/docker-texlive/blob/main/Dockerfile

After this is solved, I will submit a pull request to include the changes and have `latexindent.pl` working!

Thanks!

This issue is linked to: https://github.com/dante-ev/docker-texlive/issues/21

**Comment by cmhughes** [comment]
Thanks for this :) have you seen https://github.com/cmhughes/latexindent.pl/issues/196? Does it give you what you need?

**Comment by drupol** [comment]
Hello Chris,

I ended up using [xu-cheng/latex-docker](https://github.com/xu-cheng/latex-docker) TexLive docker which works very well with LatexIndent by default.

Thanks for your great support!

**Comment by cmhughes** [comment]
That's great, thanks for letting me know :) do let me know if you have any questions in the future :)

**Comment by drupol** [comment]
Sure, thanks!

**Comment by alexpovel** [comment]
Just to add, I tried to install those modules in a Debian-based container, but the installation script failed -- no `cpanm` installed. That's fine, I basically followed #244 . However, the installation failed at `cpanm Unicode::GCString`, since that requires `gcc`. That's not a part of normal images, but I didn't see a hint for that depedency anywhere in the documentation (saw it in the detailed Perl log installation files). I suspect this is because most documentation, e.g. the above linked PR, is based on desktop distros that ship with `gcc`.

If I see right, it might be worth hinting at the `gcc` dependency; after installing it (and `cpanm`), your [automatic installer script](https://github.com/cmhughes/latexindent.pl/blob/master/helper-scripts/latexindent-module-installer.pl) works!

**Comment by koppor** [comment]
Based on https://github.com/cmhughes/latexindent.pl/issues/196#issuecomment-616204184, I could create the `apt-get` command (by googling each module name with `debian ` added to the google word):

    sudo apt-get install -y libyaml-tiny-perl libfile-homedir-perl libunicode-linebreak-perl liblog-log4perl-perl libtest-log-dispatch-perl

**Comment by cmhughes** [comment]
Note that as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9.1 the Log4Perl module is not required for latexindent
