### ISSUE TITLE
Suggestions for improvements to how settings work

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#242]
Just a few ideas to make settings work a bit more smoothly, in my personal opinion:
* Change the default filename for local settings to `.latexindent.yaml`, `.latexindentrc`, or `.latexindentrc.yaml` or similar, which is more inline with most other programs.
* If running `latexindent` on a file in a subdirectory relative to the current directory, walk the tree from the current dir down to the directory of the file, applying settings in turn. Perhaps do this anyway, starting from `~`? Some programs do this, though it obviously incurs a slighty performance hit.
* Allow for a `.latexindent.yaml` (or similarly named, see above) file in the user's home directory, which is always read (unless, perhaps, an option explicitly barring its reading is specified).

**Comment by cmhughes** [comment]
For the first thing, you can specify `latexindent - l .localSettings.yaml my file.tex`. I should be able to tweak the script so that it looks for a hidden version of localSettings by default. 

Second bullet seems doable. I thought it already did this, but couldn't find documentation. I'll explore. 

The third bullet is already an option, see https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#indentconfig-yaml-and-indentconfig-yaml so that one is resolved.

**Comment by alexreg** [comment]
1. Yep, that sounds good re the first -- I was just thing a more appropriate name would refer to the program name, since multiple configuration files could be in the directory. If you do an `ls` it's then immediately apparent what it's for -- otherwise one might wonder `localSettings.yaml`... but for what? Certainly it would fit better with the naming scheme for other programs with configuration fles.
2. That would be super, thanks.
3. Glad to know. I suppose my only remaining point is about the slightly opaque naming (settings for *what*, to those seeing the file on the first time?).

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/e19b590e9413f628f56e5295d3822b0684d04e58 the `-l` switch indicates that the following files will be looked for, in order:
1. localSettings.yaml
2. latexindent.yaml
3. .localSettings.yaml
4. .latexindent.yaml

This will be part of the next release :) hopefully soon...

**Comment by alexreg** [comment]
That's super, thanks! It probably makes more sense to look in this order though, non?

1. latexindent.yaml
2. .latexindent.yaml
3. localSettings.yaml
4. .localSettings.yaml

Just because the more specific names are first? It's just a minor point though. Appreciate this. :-)

**Comment by cmhughes** [comment]
Thanks for the follow up :)

My main reason for this ordering is historic. The naming of localSettings
has been in place for quite some time (8 years or so), so I guess I'm keen
not to change things too much for the user base.

If I was starting from scratch, then yes, I'd go with your ordering!

It'll look for all 4 anyway, so if you only intend to specify one file,
hopefully it won't be an issue....? :)

It's on develop branch, feel free to grab it, otherwise watch this space
for release information :)

Thanks again!

**Comment by alexreg** [comment]
Ah, sounds fair enough. To be honest, the only way it would be a problem is if some other program decides to use a `localSettings.yaml` file (and insists on that name)... not likely!

So yeah, keeping that name for backwards compatibility makes sense. You can always drop support if you do a new *major version* release (or not).

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9 and uploaded to ctan.

**Comment by alexreg** [comment]
Oh, I was wondering: did you implement the second bullet point too, in this release?

**Comment by cmhughes** [comment]
I'm sorry, I don't have capacity for that at the moment.

I'm trying to overhaul the script completely at the moment, which needs to
be my focus for latexindent.

If you'd like to take it on, please do feel free. Everything you need will
be in GetYamlSettings.pm

**Comment by alexreg** [comment]
No problem at all, was just curious. I'm a bit busy with work at the moment (for which I actually need latexindent!) but when things lighten up, sure.

Incidentally, I updated all my LaTeX packages, but I seem to be stuck on v3.8.3 still, hmm. I've tried instead to clone the repo and symlinking `latexindent.pl` into my PATH, but now I'm getting `Can't locate LatexIndent/Document.pm in @INC`.

**Comment by alexreg** [comment]
Never mind; I've figured that out (adding to the `PERL5LIB` env var). Maybe CTAN will just take a while to update its cache or something?

**Comment by cmhughes** [comment]
Ctan usually takes about 24 hours :)

Yes, capacity at work is also my main issue :)
