### ISSUE TITLE
Latexindent slow in large files

### ISSUE THREAD

**Issue by obsgolem** [cmhughes/latexindent.pl#268]
Latexindent becomes almost unusably slow in files over ~500 lines (at least for me). As an example, see https://github.com/obsgolem/agitoc/blob/f6db7a405e10ed9eb6c1d8ce0896f6f621452ab2/ch9.tex which takes nearly 30 seconds to format. My settings can be found in https://github.com/obsgolem/agitoc/blob/f6db7a405e10ed9eb6c1d8ce0896f6f621452ab2/localSettings.yaml. I use latexindent through the "format on save" feature of the vscode latex-workshop plugin.

**Comment by cmhughes** [comment]
Thanks for this, and I'm sorry for the slow performance of the script. I fully acknowledge that the implementation is not ideal, and that for large files, it can be noticeably slow.

The `-m` switch (for modifying line breaks) is a particularly intense feature that requires a lot more computing time.  When I run your file using the `-m` switch on my (10-year old) Linux-based laptop, then I can confirm the timings you quote:
```
real	0m30.774s
user	0m30.687s
sys	0m0.060s
```
If I run `latexindent.pl` *without* the `-m` switch active, then the timing I receive is:
```
real	0m1.950s
user	0m1.927s
sys	0m0.021s
```

Can you configure your `vscode` to run `latexindent.pl` without the `-m` switch? If so, perhaps this is an option while doing the majority of your edits, and then run it with `-m` towards the end...?

You'll see that I am attempting to explore a different implementation in [experimental/regexp-grammars](https://github.com/cmhughes/latexindent.pl/tree/experimental/regexp-grammars ) branch. One of my hopes/goals is to improve the efficiency. I don't know if it will be successful, but be assured that I am trying.

Otherwise, if ever you have proposals for how to improve the script, please do submit pull requests to the `develop` branch. And if you find a tool that does things more efficiently, do let me know :)

**Comment by obsgolem** [comment]
Thanks for the response. For me, the `-m` switch is actually the most useful feature of latexindent, followed shortly by auto-alignment of matrices and align environments, so I really want to keep it on. For the time being I have split up my large file into a bunch of smaller sections and this takes care of the issue. If you want to keep this issue open to track this particular performance issue that is fine with me, or I could close it.

**Comment by cmhughes** [comment]
Thanks. There's no need for an issue on this, as it's always on my mind :)

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/b7790e8707eb261fbe74f1afbc5e44f7e17a3871, the `-m` switch routine is a lot more efficient. 

Running `latexindent.pl` with the `-m` switch on [your example](https://github.com/obsgolem/agitoc/blob/f6db7a405e10ed9eb6c1d8ce0896f6f621452ab2/ch9.tex) now gives the following timing:
```
real	0m2.346s
user	0m2.280s
sys	0m0.036s
```
Quite an improvement from the above!

It'll be part of the next release, but if you're welcome to pull from `develop` in the meantime. 

Thanks for raising this, and for the helpful example.

**Comment by leanhdung1994** [comment]
@cmhughes With the help of LLM, I wonder if it is reasonable to re-write latexindent in Rust for performance speedup.

**Comment by cmhughes** [comment]
Have you tried V4.0?

**Comment by cmhughes** [comment]
Also, feel free to rewrite it!

**Comment by cmhughes** [comment]
Why would it be quicker in Rust?

**Comment by leanhdung1994** [comment]
> Have you tried V4.0?

The V4.0 is indeed very fast:
````ps
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS P:\Personal projects\test performance of latexindent> powershell -Command "Measure-Command { latexindent '.\arXiv-1711.07597v2\paperSS122018arxivv2.tex' } | Select-Object -ExpandProperty TotalSeconds"
UTF-8 "\x95" does not map to Unicode at C:/Users/Akira/AppData/Local/Programs/MiKTeX/scripts/latexindent/LatexIndent/FileExtension.pm line 196, <$fh> line 18395.
UTF-8 "\x95" does not map to Unicode at C:/Users/Akira/AppData/Local/Programs/MiKTeX/scripts/latexindent/LatexIndent/FileExtension.pm line 196, <$fh> line 18395.
23.6224204
PS P:\Personal projects\test performance of latexindent>
````

It takes around 25 seconds on this [tex file](https://arxiv.org/src/1711.07597) with 36.192 lines.

**Comment by cmhughes** [comment]
Yep, and I think that's pretty good 😊

**Comment by leanhdung1994** [comment]
@cmhughes I am very impressed with latexindent's extensive capabilities and the new speed improvement that I have posted on reddit https://www.reddit.com/r/LaTeX/comments/1sn6m3n/latexindent_v40_is_fast_and_still_the_most/.

**Comment by cmhughes** [comment]
THANK YOU! I really appreciate this, you've made my day 😊 Its great to know that you appreciate latexindent 😊🎉💯

**Comment by leanhdung1994** [comment]
It is unbelievable that you have actively single-handed this project since 2012. Thank you very much for your dedicated contribution. I am deeply grateful.

**Comment by cmhughes** [comment]
In V4.0, your file runs in the following time
```
real	0m0.612s
user	0m0.601s
sys	0m0.011s
```
