### ISSUE TITLE
Beamer items with overlay specifications not treated as items

### ISSUE THREAD

**Issue by jameswhqi** [cmhughes/latexindent.pl#307]
original .tex code
--
```latex
\begin{itemize}
\item One
\item<2-> Two
\item Three
\item <4-> Four
\end{itemize}
```

yaml settings
--
```yaml
defaultIndent: "  "
```

actual/given output
--
```latex
\begin{itemize}
  \item One
        \item<2-> Two
  \item Three
  \item <4-> Four
\end{itemize}
```

desired or expected output
--
```latex
\begin{itemize}
  \item One
  \item<2-> Two
  \item Three
  \item <4-> Four
\end{itemize}
```

**Comment by cmhughes** [comment]
Hello,
Thanks for this. 

As of https://github.com/cmhughes/latexindent.pl/commit/2f407617f4ab81156af85b2a1e541c78e6718099 I've adjusted the `fineTuning` field so that your output will be as desired, and users can tweak the `canBeFollowedBy` field. 

This will be part of the next release.

Thanks again!

**Comment by cmhughes** [comment]
This needs to stay open until released :)

**Comment by cmhughes** [comment]
Implemented at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.13.3, upload to ctan imminent.
